### PR TITLE
Language consistency

### PR DESCRIPTION
**Pull request by jeckodevelopment**
#### Summary of Changes
Changed `our site` in `this site` according other strings in the CMS

### CODE REVIEW

**Comment by MATsxm** [comment]
@jeckodevelopment 
when you're making this kind of changes, thank you also to report them on Crowdin thanks.

**Comment by jeckodevelopment** [comment]
How to do it?

**Comment by MATsxm** [comment]
just report as an issue like you did for the link...
just to be sure I don't miss anything to do/check

**Comment by jeckodevelopment** [comment]
ok! Thank you for noticing!

**Comment by nikosdion** [comment]
@MATsxm Doesn't Crowding show the modified strings as untranslated automatically? Transifex has been doing that for nearly two years. I would assume that they have feature parity at this point.

**Comment by MATsxm** [comment]
it depends... you have the choice. Here it is the case (I had the changes as untranslated) and please do not compare to Transifex... Crowdin is a platform orriented Translators and Managers :wink:

**Comment by nikosdion** [comment]
Here's the thing. I am a developer. My job is to *develop software*. Today I spent 10' managing language PRs *for French*.

I will remove all translation files from this repository. You guys are the translation team, you figure out how to deliver translations without me wasting my time managing languages.

**Comment by MATsxm** [comment]
easy... just like for other projects... I can do the job.
Who's asking you to deal with lg PR's?

**Comment by nikosdion** [comment]
The 12 emails I got while I was having lunch. I can ignore all email from this project but when you screw up something related to the built package I am the one getting the blame, not you. See the problem? I ultimately have to deal with every PR no matter who makes it, what it's about and who merges it.

**Comment by nikosdion** [comment]
What is REALLY required is 1. an automated way to push English strings from the repo to Crowdin 2. an automated way for you to be notified whenever there are changed strings (it's insane asking people to file a PR AND a Crowdin issue for every language string change!) and 3. an automated way to pull translations and update the XML files.

The problem with 1 & 3 is that they require an API key which can't be committed to the repo. I could try to automate that but I'm effectively solving the same problem I have solved 5 years ago. It's uninteresting to me and irrelevant to this plugin so I just won't spend time on it. Hence providing only en_GB in this repo. If someone wants to automate these steps, feel free. Until then and as long as I'm assigned to manage this code repo I'll only include en_GB.

As for problem 2 it's a major deficiency in Crowdin. They should mark the string as untranslated once the source changes. Having to manually mark modified strings as such is insane for developers and translators alike. I know that Joomla has been doing that for ten years but this doesn't mean that it makes any sense. As a former business productivity consultant I would mark the time spent towards that effort as "unproductive" and propose an action plan to eliminate it.

Speaking of Crowdin, thank you for pointing out that what I did earlier today was actually a *translation*. Crowdin was telling me it's a "suggestion". That of course raises the question, if any random person _who just created an account_ (like me) can come into a project and provide translations without having to be accepted by a manager how exactly do you guarantee the quality of the translations or that no spam ends up being included? That's a bit scary. I am more inclined to believe that what I did was not a translation but something else. Can you please elaborate what happens when Joe Random appears out of nowhere and starts to translate a project he's not been added to by a manager?

**Comment by jeckodevelopment** [comment]
> Here's the thing. I am a developer. My job is to develop software. Today I spent 10' managing language PRs for French.
I'm here also to help you with all this stuff @nikosdion

**Comment by mbabker** [comment]
1 is implemented already for existing files.  The sync script isn't written in a way that it could try to auto-create new files in Crowdin, so that needs manual intervention (MAT, Luca, or even myself could do that).  Once created, you add the path mappings to the `crowdin.yaml` file and everything is good going forward.

For 2, Crowdin will send email notifications on projects you're watching when there are changes (and other activity depending on your settings).  Even though I don't do much for translations, I've set up a couple projects with different notification levels to try and understand different workflows and tools available.

3 is partially implemented with the sync script.  I sent you the API key via PM.  That will automate downloads for you.  As for the XML manifest changes, for the workflow I've been using, it's not a step I have implemented right now (I've been shoving everything in the extension's local language directory versus the global directory).  The folks managing [JoRobo](https://github.com/joomla-projects/jorobo) have a task that can automatically build that section of the manifest when packaging, presumably something similar could be done as a Phing task.  The only "issue" with that approach though is it makes the repo run in a state where the code isn't installable as is; you'd HAVE to run a packaging script to be able to get useable manifests.

Unfortunately I think we're going to go through some growing pains figuring out an optimal translation workflow for this repo.  Weblinks translations are still managed within the CMS and part of the translation team workflows, and the extensions I'm maintaining with Crowdin integration are specialized purpose so don't need to worry about things like separately installable packages.

**Pull request merged**
