### PR TITLE
Create fr-FR.plg_authentication_facebook.sys.ini

### PR DESCRIPTION
**Pull request by MATsxm**
I don't understand why I can't commit it to previous PR...

### CODE REVIEW

**Comment by nikosdion** [comment]
You can't commit to the previous PR because @jeckodevelopment merged it already. When a PR is merged it's closed therefore you can't commit anything :)

**Comment by nikosdion** [comment]
Unless you mean PR gh-8, in which case it's because you used the GitHub button to upload a file. You can only upload one thing at a time.

**Comment by nikosdion** [comment]
I also see a fatal flaw in the Crowdin integration: every language change needs a PR which requires a developer to merge it. That's a massive waste of time!

Transifex has a far better workflow. I can simply run `tx pull` to pull all of the latest translations into the working copy and then simply commit the changes. Likewise, when there are new translations I just have to do a `tx push` to update TX of the new and modified language keys. If Crowding doesn't offer this fundamental sync capability why are we using it? If we end up with 80 languages I will have to spend all of my time managing language PRs instead of doing real work.

**Comment by MATsxm** [comment]
@nikosdion 
for devs questions... see with Crowdin.
I'm managing more than 80 projects on nearly 20 diff platforms (private or public) and at this point, even if each ones have + and -, crowdin is easier to manage, with a better support and with more QA/QC results in a TRANSLATOR point of view.
Choices must be done and sorry but I will always look for the confort of translators first, and won't start a sterile war again :wink: just doin my job.

**Comment by mbabker** [comment]
@nikosdion You should be able to run a simple pull command after #5 was merged.

**Comment by mbabker** [comment]
Oh, nevermind.  I'm working my way from the top of my GItHub email filter, hadn't seen the comments there yet.

**Pull request merged**
